[project]
name = "s3serve"
version = "0.1.0"
description = "Simple S3 Server"
authors = [{ name = "Rob van der Leek", email = "robvanderleek@gmail.com" }]
requires-python = ">=3.11,<3.14"
readme = "README.md"
license = "GPL-3.0-or-later"

dependencies = [
    "boto3>=1.35.60",
    "boto3-stubs-lite[s3]>=1.35.64",
    "fastapi[standard]>=0.115.5",
    "pillow>=11.1.0",
    "pydantic-settings>=2.6.1",
    "pyperclip>=1.9.0",
    "typer>=0.15.1",
]

[project.urls]
Homepage = "https://github.com/robvanderleek/s3serve"
Repository = "https://github.com/robvanderleek/s3serve.git"

[project.scripts]
s3serve = "s3serve.__main__:main"

[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "moto[s3]>=5.0.20",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.11.16,<0.13.0"]
build-backend = "uv_build"

[tool.semantic_release]
branch = "main"
version_toml = [ "pyproject.toml:tool.poetry.version" ]
version_variables = [ "s3serve/version.py:version" ]
upload_to_repository = false
upload_to_release = false
allow_zero_version = true
