name: 'main'

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Sources'
      uses: actions/checkout@v4

    - name: 'Set up Python'
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: 'Set up Poetry'
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3

    - name: 'Install dependencies'
      run: poetry install --no-interaction --no-root

    - name: 'Run unit-tests'
      run: poetry run pytest
